---
title: "The Un-bee-lievable Truth: How Data Science Detects Fake Stingless Bee Honey"
author: "Wai Yan Lee (Vienne)"
date: "1/13/2026"
#listing:
  #contents: posts
  #sort: "date desc"
  #type: default
  #categories: true
  #sort-ui: false
  #filter-ui: false
page-layout: full
title-block-banner: true
toc: true
bibliography: reference.bib
nocite: |
  @*
---

Have you looked at a jar of honey labeled ‘100% Pure’ and wonder if it is the real deal? Do you then wonder if it is worth the premium price? You are right to be skeptical as food fraud is a common issue. When it comes to stingless bee honey – a rare superfood that has an unique taste and health benefits – the high value makes it easy to be targeted for fraud. Adulteration with other substance like water or apple cider vinegar can cut costs and mass-product a product to make profit while able to mimic the texture and taste to fool our senses. This is where human perception fails. Fortunately, modern data science is here to solve the problem, specifically for stingless bee honey. With a simple light scanner and powerful machine learning algorithms, adulteration can detect and measured with high accuracy. This blog will walk you step-by-step on modern science solves food fraud, from data collection to training algorithm to learn hidden patterns and spot the fakes. The goal is to use data science to detect fake honey and measure the amount of other substances were added.

### What is Stingless Bee Honey? Why This Matter?

You might not have heard of stingless bees, but they are very similar to the common honeybee. Unlike normal bees, they have a reduced stinger, so they don’t use it for defense. Instead, they protect their nests by biting, discharging acid, or using resin. They are mainly located in tropical and subtropical regions.

Stingless bee honey is considered rare because of both geographic limitations and low production. The stingless beehive produces only around 0.5-2 liters per year, compared to 20-40 liters per year from a normal honeybee hive. Therefore, stingless bee honey cannot be produced on an industrial scale. The honey is not only used as a natural sweetener but has a distinct taste and has tremendous health benefits. Its rareness, medicinal properties, and unique taste make it very valuable and high demand.

High demand and high value products are often targets for adulteration and fraud; stingless bee honey is no exception. It is important to spot the fake honey to protect consumers and beekeepers. Honey adulteration affects consumers, beekeepers, scientific and medicinal research. Consumers are at a disadvantage when purchasing adulterated honey believing it’s pure. This is because adulterated honey lacks the natural compounds that consumers are seeking for health benefits. Beekeepers suffer economic losses due to unfair competition. When consumers repeatedly discover fake honey in the market, they might stop trusting all honey products. Finally, researchers rely on authentic stingless bee honey to accurately analyze its components and health-related properties. Using fake stingless bee honey can lead to misleading conclusions and inaccurate results.

### Data Collection

Before diving into the analysis of the stingless bee honey, we first need to collect the data. Pure stingless bee honey samples were collected from three towns in the northern part of Malaysia: Merbok, Kodiang, and Teloi Tua. A total of 250 samples are used in this analysis. They include:

-   **Three pure samples**: Pure stingless bee honey from the three towns in the northern part of Malaysia

-   **Two pure adulteration samples**: Samples of water and apple cider vinegar

-   **120 samples with vary adulteration**: They were created by adding increasing amount of water to each pure honey sample. For instance,  1 milliliter of water added in each pure stingless bee honey, … up to 20 milliliters of water added in each pure stingless bee honey

Once sample data is collected, they are systematically labeled by the source and levels of adulterant added. To ensure the substances were processed properly in the honey, the altered samples are stirred and stored in the dark for 24 hours before beginning the analysis to ensure stable readings.

### Measurements

This analysis will be focusing on two measurements: Brix and Acidity.

-   Brix measures the level of sugar and concentration in a liquid. Think of it as sweetness. Higher brix means more sugar which indicates the liquid is sweeter. Alternatively, lower brix means less sugar which indicates the liquid is less sweet.

-   Acidity measures using a standard pH meter. Think of it as sourness. High acidity indicates very sour while low acidity indicates dullness.

### Data Cleaning

The current samples are not ready to be analyzed; raw data and clean data are needed. First, to transform the existing samples into raw data, a simple light “scanner” (scientifically known as Near-Infrared Spectroscopy) is used. This is a scanner that shines a spectrum of light that human eyes cannot see through the stingless bee honey samples and observes how each molecules reacts. Each molecule interacts differently with the light; some might absorb more than others. The scanner measures how much colours each molecule absorbs. The scanner produced thousands of data; known as the ‘light fingerprint’.

Secondly, Principal Component Analysis (PCA) is used to convert thousands of raw data into smaller set of data by grouping similar data together, keeping the biggest differences, and removing data that is irrelevant. Essentially, PCA performs the analysis to clean up the messy data and return a smaller, cleaner dataset that only contains the most important part so it’s easier to understand.

### The Analysis

To properly analyze and interpret the data, a set of machine learning algorithm is needed to learn and explain the hidden patterns. Two main models were used: combination of Principal Component Analysis (PCA) and linear discriminant analysis (LDA) to build a classifier (PCA-LDA) and a partial least squares regression (PLSR) as the quantifier.

Linear discriminant analysis (LDA) is a supervised machine learning technique for dimensionality reduction and classification. Imagine you have a pile of socks in a big box. The technique essentially groups similar socks together and set the different socks far apart. This technique is combined with PCA. It learned hidden patterns and classified the boundaries between groups with the labels (pure honey, water-adulterated vs vinegar-adulterated).

To take the analysis one step further, the researchers use partial least squares regression (PLSR) model to identify the exact amount of adulterant added into the honey. PLSR is a model that make predictions from many related measurements. For instance, you are trying to drive from point A to point B using GPS. There are many different routes you can take but GPS takes in all possible routes and gives you the most optimal one. This model took in the raw data and learned hidden patterns then predicted how much adulterant added into the honey. Researchers found that using a model with 7 components achieved a very strong correlation between predicted and actual adulteration level. This means the predicted percentages of the adulterants matched the actual values almost perfectly.

### Results & Takeaway

The PCA-LDA model achieved 100 % accuracy on distinguishing pure and adulterated stingless bee honey. The PLSR model is able to accurately quantify the percentage of adulteration with high correlation coefficients (\~0.993) and low errors (RMSECV = 1.686%). This indicates the model’s reliability.

The goal of this research is to demonstrate how data science tools can detect and measure fake honey. This research provides the truth when our senses are unreliable. The model performed with high accuracy with stingless bee honey; imagine how many other products these models can apply to. With this truth, it allows customers to purchase premium stingless bee honey with confidence and protect the beekeepers by showing the authenticity of their honey. The next time you choose a premium product, know that science is working to ensure its label tells the truth.
